[package]
name = "adafruit_gps"
version = "0.1.0"
authors = ["Matt Barson <matt.barson@gmail.com>"]
edition = "2018"
licence = "MIT"
description = "Port of the adafruit python libary for their Ultimate GPS or Adafruit Mini GPS PA1010D."

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
